linters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign
    - gofmt
    - goimports

run:
  timeout: 5m

issues:
  exclude-dirs:
    - build
    - frontend/node_modules
    - frontend/dist
