// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CloseLocalTerminal(arg1:string):Promise<void>;

export function CloseSSH(arg1:string):Promise<void>;

export function Connect(arg1:main.ConnectRequest):Promise<main.ConnectResult>;

export function DeleteSession(arg1:string):Promise<void>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<main.RemoteFile>>;

export function ListSessions():Promise<Array<config.SessionProfile>>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<string>;

export function ResizeLocalTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeSSH(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveSession(arg1:config.SessionProfile):Promise<void>;

export function SelectKeyFile():Promise<string>;

export function StartLocalTerminal():Promise<string>;

export function TrustHost(arg1:string):Promise<void>;

export function TrustHostDespiteChange(arg1:string):Promise<void>;

export function WriteLocalTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteSSH(arg1:string,arg2:string):Promise<void>;
