// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseLocalTerminal(arg1) {
  return window['go']['main']['App']['CloseLocalTerminal'](arg1);
}

export function CloseSSH(arg1) {
  return window['go']['main']['App']['CloseSSH'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function ListRemoteDir(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteDir'](arg1, arg2);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ReadRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['ReadRemoteFile'](arg1, arg2);
}

export function ResizeLocalTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeLocalTerminal'](arg1, arg2, arg3);
}

export function ResizeSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSSH'](arg1, arg2, arg3);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SelectKeyFile() {
  return window['go']['main']['App']['SelectKeyFile']();
}

export function StartLocalTerminal() {
  return window['go']['main']['App']['StartLocalTerminal']();
}

export function TrustHost(arg1) {
  return window['go']['main']['App']['TrustHost'](arg1);
}

export function TrustHostDespiteChange(arg1) {
  return window['go']['main']['App']['TrustHostDespiteChange'](arg1);
}

export function WriteLocalTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteLocalTerminal'](arg1, arg2);
}

export function WriteRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteRemoteFile'](arg1, arg2, arg3);
}

export function WriteSSH(arg1, arg2) {
  return window['go']['main']['App']['WriteSSH'](arg1, arg2);
}
