// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseLocalTerminal(arg1) {
  return window['go']['main']['App']['CloseLocalTerminal'](arg1);
}

export function CloseSSH(arg1) {
  return window['go']['main']['App']['CloseSSH'](arg1);
}

export function CloseSerial(arg1) {
  return window['go']['main']['App']['CloseSerial'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectSerial(arg1, arg2) {
  return window['go']['main']['App']['ConnectSerial'](arg1, arg2);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetClipboardText() {
  return window['go']['main']['App']['GetClipboardText']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListRemoteDir(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteDir'](arg1, arg2);
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ReadRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['ReadRemoteFile'](arg1, arg2);
}

export function ResizeLocalTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeLocalTerminal'](arg1, arg2, arg3);
}

export function ResizeSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSSH'](arg1, arg2, arg3);
}

export function SaveGroup(arg1) {
  return window['go']['main']['App']['SaveGroup'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function SelectKeyFile() {
  return window['go']['main']['App']['SelectKeyFile']();
}

export function StartLocalTerminal(arg1) {
  return window['go']['main']['App']['StartLocalTerminal'](arg1);
}

export function TrustHost(arg1) {
  return window['go']['main']['App']['TrustHost'](arg1);
}

export function TrustHostDespiteChange(arg1) {
  return window['go']['main']['App']['TrustHostDespiteChange'](arg1);
}

export function UploadRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadRemoteFile'](arg1, arg2, arg3);
}

export function WriteLocalTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteLocalTerminal'](arg1, arg2);
}

export function WriteRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteRemoteFile'](arg1, arg2, arg3);
}

export function WriteSSH(arg1, arg2) {
  return window['go']['main']['App']['WriteSSH'](arg1, arg2);
}

export function WriteSerial(arg1, arg2) {
  return window['go']['main']['App']['WriteSerial'](arg1, arg2);
}
