// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CloseLocalTerminal(arg1:string):Promise<void>;

export function CloseSSH(arg1:string):Promise<void>;

export function CloseSerial(arg1:string):Promise<void>;

export function Connect(arg1:main.ConnectRequest):Promise<main.ConnectResult>;

export function ConnectSerial(arg1:string,arg2:number):Promise<string>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteLocalShellProfile(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function ExportConfigFile():Promise<string>;

export function GetClipboardText():Promise<string>;

export function GetOSUsername():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetSettings():Promise<config.Settings>;

export function GetStartupDir():Promise<string>;

export function GetVersion():Promise<string>;

export function ImportConfigFile():Promise<string>;

export function ListGroups():Promise<Array<config.SessionGroup>>;

export function ListLocalShellProfiles():Promise<Array<config.LocalShellProfile>>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<main.RemoteFile>>;

export function ListSerialPorts():Promise<Array<string>>;

export function ListSessions():Promise<Array<config.SessionProfile>>;

export function ReadImageFile(arg1:string):Promise<string>;

export function ReadLocalFile(arg1:string):Promise<string>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<string>;

export function ResizeLocalTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeSSH(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveGroup(arg1:config.SessionGroup):Promise<void>;

export function SaveLocalShellProfile(arg1:config.LocalShellProfile):Promise<void>;

export function SaveSession(arg1:config.SessionProfile):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<string>;

export function SelectAnyFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectImageFile():Promise<string>;

export function SelectKeyFile():Promise<string>;

export function StartLocalTerminal(arg1:string,arg2:string):Promise<string>;

export function TrustHost(arg1:string):Promise<void>;

export function TrustHostDespiteChange(arg1:string):Promise<void>;

export function UploadRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteLocalFile(arg1:string,arg2:string):Promise<void>;

export function WriteLocalTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteSSH(arg1:string,arg2:string):Promise<void>;

export function WriteSerial(arg1:string,arg2:string):Promise<void>;
